apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: evaluations
spec:
  dspVersion: v2
  objectStorage:
    externalStorage:
      bucket: mlpipeline
      host: s4.evaluations.svc.cluster.local
      port: "7480"
      scheme: http
      s3CredentialsSecret:
        secretName: ds-pipeline-s3-dspa
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
  podToPodTLS: false
