/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUnderwriterIndexRouteImport } from './routes/_authenticated/underwriter/index'
import { Route as AuthenticatedLoanOfficerIndexRouteImport } from './routes/_authenticated/loan-officer/index'
import { Route as AuthenticatedCeoIndexRouteImport } from './routes/_authenticated/ceo/index'
import { Route as AuthenticatedBorrowerIndexRouteImport } from './routes/_authenticated/borrower/index'
import { Route as AuthenticatedUnderwriterApplicationIdRouteImport } from './routes/_authenticated/underwriter/$applicationId'
import { Route as AuthenticatedLoanOfficerApplicationIdRouteImport } from './routes/_authenticated/loan-officer/$applicationId'
import { Route as AuthenticatedCeoAuditRouteImport } from './routes/_authenticated/ceo/audit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnderwriterIndexRoute =
  AuthenticatedUnderwriterIndexRouteImport.update({
    id: '/underwriter/',
    path: '/underwriter/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoanOfficerIndexRoute =
  AuthenticatedLoanOfficerIndexRouteImport.update({
    id: '/loan-officer/',
    path: '/loan-officer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeoIndexRoute = AuthenticatedCeoIndexRouteImport.update({
  id: '/ceo/',
  path: '/ceo/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBorrowerIndexRoute =
  AuthenticatedBorrowerIndexRouteImport.update({
    id: '/borrower/',
    path: '/borrower/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUnderwriterApplicationIdRoute =
  AuthenticatedUnderwriterApplicationIdRouteImport.update({
    id: '/underwriter/$applicationId',
    path: '/underwriter/$applicationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoanOfficerApplicationIdRoute =
  AuthenticatedLoanOfficerApplicationIdRouteImport.update({
    id: '/loan-officer/$applicationId',
    path: '/loan-officer/$applicationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeoAuditRoute = AuthenticatedCeoAuditRouteImport.update({
  id: '/ceo/audit',
  path: '/ceo/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ceo/audit': typeof AuthenticatedCeoAuditRoute
  '/loan-officer/$applicationId': typeof AuthenticatedLoanOfficerApplicationIdRoute
  '/underwriter/$applicationId': typeof AuthenticatedUnderwriterApplicationIdRoute
  '/borrower/': typeof AuthenticatedBorrowerIndexRoute
  '/ceo/': typeof AuthenticatedCeoIndexRoute
  '/loan-officer/': typeof AuthenticatedLoanOfficerIndexRoute
  '/underwriter/': typeof AuthenticatedUnderwriterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/ceo/audit': typeof AuthenticatedCeoAuditRoute
  '/loan-officer/$applicationId': typeof AuthenticatedLoanOfficerApplicationIdRoute
  '/underwriter/$applicationId': typeof AuthenticatedUnderwriterApplicationIdRoute
  '/borrower': typeof AuthenticatedBorrowerIndexRoute
  '/ceo': typeof AuthenticatedCeoIndexRoute
  '/loan-officer': typeof AuthenticatedLoanOfficerIndexRoute
  '/underwriter': typeof AuthenticatedUnderwriterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/ceo/audit': typeof AuthenticatedCeoAuditRoute
  '/_authenticated/loan-officer/$applicationId': typeof AuthenticatedLoanOfficerApplicationIdRoute
  '/_authenticated/underwriter/$applicationId': typeof AuthenticatedUnderwriterApplicationIdRoute
  '/_authenticated/borrower/': typeof AuthenticatedBorrowerIndexRoute
  '/_authenticated/ceo/': typeof AuthenticatedCeoIndexRoute
  '/_authenticated/loan-officer/': typeof AuthenticatedLoanOfficerIndexRoute
  '/_authenticated/underwriter/': typeof AuthenticatedUnderwriterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/ceo/audit'
    | '/loan-officer/$applicationId'
    | '/underwriter/$applicationId'
    | '/borrower/'
    | '/ceo/'
    | '/loan-officer/'
    | '/underwriter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/ceo/audit'
    | '/loan-officer/$applicationId'
    | '/underwriter/$applicationId'
    | '/borrower'
    | '/ceo'
    | '/loan-officer'
    | '/underwriter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/ceo/audit'
    | '/_authenticated/loan-officer/$applicationId'
    | '/_authenticated/underwriter/$applicationId'
    | '/_authenticated/borrower/'
    | '/_authenticated/ceo/'
    | '/_authenticated/loan-officer/'
    | '/_authenticated/underwriter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/underwriter/': {
      id: '/_authenticated/underwriter/'
      path: '/underwriter'
      fullPath: '/underwriter/'
      preLoaderRoute: typeof AuthenticatedUnderwriterIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loan-officer/': {
      id: '/_authenticated/loan-officer/'
      path: '/loan-officer'
      fullPath: '/loan-officer/'
      preLoaderRoute: typeof AuthenticatedLoanOfficerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceo/': {
      id: '/_authenticated/ceo/'
      path: '/ceo'
      fullPath: '/ceo/'
      preLoaderRoute: typeof AuthenticatedCeoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrower/': {
      id: '/_authenticated/borrower/'
      path: '/borrower'
      fullPath: '/borrower/'
      preLoaderRoute: typeof AuthenticatedBorrowerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/underwriter/$applicationId': {
      id: '/_authenticated/underwriter/$applicationId'
      path: '/underwriter/$applicationId'
      fullPath: '/underwriter/$applicationId'
      preLoaderRoute: typeof AuthenticatedUnderwriterApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loan-officer/$applicationId': {
      id: '/_authenticated/loan-officer/$applicationId'
      path: '/loan-officer/$applicationId'
      fullPath: '/loan-officer/$applicationId'
      preLoaderRoute: typeof AuthenticatedLoanOfficerApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceo/audit': {
      id: '/_authenticated/ceo/audit'
      path: '/ceo/audit'
      fullPath: '/ceo/audit'
      preLoaderRoute: typeof AuthenticatedCeoAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCeoAuditRoute: typeof AuthenticatedCeoAuditRoute
  AuthenticatedLoanOfficerApplicationIdRoute: typeof AuthenticatedLoanOfficerApplicationIdRoute
  AuthenticatedUnderwriterApplicationIdRoute: typeof AuthenticatedUnderwriterApplicationIdRoute
  AuthenticatedBorrowerIndexRoute: typeof AuthenticatedBorrowerIndexRoute
  AuthenticatedCeoIndexRoute: typeof AuthenticatedCeoIndexRoute
  AuthenticatedLoanOfficerIndexRoute: typeof AuthenticatedLoanOfficerIndexRoute
  AuthenticatedUnderwriterIndexRoute: typeof AuthenticatedUnderwriterIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCeoAuditRoute: AuthenticatedCeoAuditRoute,
  AuthenticatedLoanOfficerApplicationIdRoute:
    AuthenticatedLoanOfficerApplicationIdRoute,
  AuthenticatedUnderwriterApplicationIdRoute:
    AuthenticatedUnderwriterApplicationIdRoute,
  AuthenticatedBorrowerIndexRoute: AuthenticatedBorrowerIndexRoute,
  AuthenticatedCeoIndexRoute: AuthenticatedCeoIndexRoute,
  AuthenticatedLoanOfficerIndexRoute: AuthenticatedLoanOfficerIndexRoute,
  AuthenticatedUnderwriterIndexRoute: AuthenticatedUnderwriterIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
